# This compose file is currently only suitable for development use!

version: "3.7"
services:
  core:
    build:
      context: .
      args:
        pipenv_flags: --three --dev
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_SU_NAME=${DJANGO_SU_NAME}
      - DJANGO_SU_PASSWORD=${DJANGO_SU_PASSWORD}
      - DJANGO_SU_EMAIL=${DJANGO_SU_EMAIL}
      - DJANGO_SETTINGS_MODULE=Harvest.settings.development
    volumes:
      - .:/app
    command: pipenv run gunicorn -b 0.0.0.0:8001 --reload Harvest.wsgi:application
    ports:
      - 8001:8001
    networks:
      - backend
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - backend

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/usr/share/nginx/harvest/static
    ports:
      - "80:80"
    networks:
      - backend
    depends_on:
      - core

# Development Only!
  db-admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: root@email.com
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
    ports:
      - "8080:80"
    networks:
      - backend

networks:
  backend:
