- name: Install virtualenv
  become: yes
  pip: name=virtualenv executable=pip3

- name: Create virtualenv and install requirements
  pip:
    requirements: /vagrant/requirements.txt
    virtualenv: "{{ venv }}"
    virtualenv_python: python3
    virtualenv_site_packages: yes

- name: Install alcazard requirements
  pip:
    requirements: /vagrant/alcazard/requirements.txt
    virtualenv: "{{ venv }}"

- name: Put django_env settings file
  template:
    src: django-env.j2
    dest: /vagrant/django_env

- name: Globally install psycopg2 for ansible
  become: yes
  pip: name=psycopg2

- name: Create Postgres user
  become: yes
  become_user: postgres
  postgresql_user:
    name: vagrant
    role_attr_flags: SUPERUSER

- name: Create Postgres DB
  become: yes
  become_user: postgres
  postgresql_db:
    name: harvest
    owner: vagrant

- name: Migrate Django
  command: "{{ venv }}/bin/python manage.py migrate"
  args:
    chdir: /vagrant

- name: Create Django superuser
  command: "{{ venv }}/bin/python manage.py create_harvest_superuser --exists-ok admin admin"
  args:
    chdir: /vagrant

- name: Configure Django Clcazar client
  command: "{{ venv }}/bin/python manage.py config_alcazar_client"
  args:
    chdir: /vagrant

- name: Config alcazard
  command: "{{ venv }}/bin/python alcazard.py --state state/ config"
  args:
    chdir: /vagrant/alcazard
